name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install
        run: |
          pip install -U pip
          pip install -r requirements.txt
      - name: Lint
        run: ruff check . || true
      - name: Test
        run: pytest -q

  bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/bot
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install
        run: |
          pip install -U pip
          pip install -r requirements.txt
      - name: Lint
        run: ruff check . || true

  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build images
        run: |
          docker build -t quantumx-backend:ci ./apps/backend
          docker build -t quantumx-bot:ci ./apps/bot
          docker build -t quantumx-web:ci ./apps/web
