name: SLSA generic generator
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - uses: actions/checkout@v4

      - name: Build artifacts
        run: |
          # Замените на реальные шаги сборки вашего проекта
          echo "artifact1" > artifact1
          echo "artifact2" > artifact2

      - name: Generate subject for provenance
        id: hash
        shell: bash
        run: |
          set -euo pipefail

          # Найти артефакты в корне репозитория (поддерживает пробелы в именах)
          mapfile -d '' files < <(find . -maxdepth 1 -type f -name 'artifact*' -print0)

          if [ "${#files[@]}" -eq 0 ]; then
            echo "digests=" >> "${GITHUB_OUTPUT}"
            exit 0
          fi

          # Нормализовать имена и отсортировать для детерминированности
          real_files=()
          for p in "${files[@]}"; do
            p="${p#./}"
            real_files+=("$p")
          done
          IFS=$'\n' sorted=($(printf "%s\n" "${real_files[@]}" | sort))
          unset IFS

          # Конкатенируем hex sha256-хэши и base64-кодируем без переносов
          hashes=""
          for f in "${sorted[@]}"; do
            h=$(sha256sum "$f" | awk '{print $1}')
            hashes="${hashes}${h}"
          done

          encoded=$(printf "%s" "$hashes" | base64 | tr -d '\n')
          echo "digests=${encoded}" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true

  publish:
    runs-on: ubuntu-latest
    needs: [provenance]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Перезаписать файл, закоммитить и запушить
        run: |
          cat > .github/workflows/generator-generic-ossf-slsa3-publish.yml <<'YAML'
name: SLSA generic generator
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - uses: actions/checkout@v4

      - name: Build artifacts
        run: |
          # Замените на реальные шаги сборки вашего проекта
          echo "artifact1" > artifact1
          echo "artifact2" > artifact2

      - name: Generate subject for provenance
        id: hash
        shell: bash
        run: |
          set -euo pipefail

          # Найти артефакты в корне репозитория (поддерживает пробелы в именах)
          mapfile -d '' files < <(find . -maxdepth 1 -type f -name 'artifact*' -print0)

          if [ "${#files[@]}" -eq 0 ]; then
            echo "digests=" >> "${GITHUB_OUTPUT}"
            exit 0
          fi

          # Нормализовать имена и отсортировать для детерминированности
          real_files=()
          for p in "${files[@]}"; do
            p="${p#./}"
            real_files+=("$p")
          done
          IFS=$'\n' sorted=($(printf "%s\n" "${real_files[@]}" | sort))
          unset IFS

          # Конкатенируем hex sha256-хэши и base64-кодируем без переносов
          hashes=""
          for f in "${sorted[@]}"; do
            h=$(sha256sum "$f" | awk '{print $1}')
            hashes="${hashes}${h}"
          done

          encoded=$(printf "%s" "$hashes" | base64 | tr -d '\n')
          echo "digests=${encoded}" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true
YAML

          git add .github/workflows/generator-generic-ossf-slsa3-publish.yml
          git commit -m "fix(workflow): valid YAML for SLSA provenance"
          git push origin HEAD

      - name: Посмотреть недавние запуски workflow
        run: gh run list --workflow generator-generic-ossf-slsa3-publish.yml --limit 10 --json databaseId,id,event,headBranch,status,conclusion,createdAt

      - name: Получить id последнего запуска и показать логи
        run: |
          run_id=$(gh run list --workflow generator-generic-ossf-slsa3-publish.yml --limit 1 --json databaseId --jq '.[0].databaseId')
          gh run view "$run_id" --json jobs,check_suite,head_commit,status,conclusion,createdAt
